<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllUsersExceptCurrentLogged($userId) {
        $sql = 'SELECT u.id, u.username, u.followersCounter, u.followingCounter, u.instaCounter
                    FROM users AS u
                    WHERE u.id != :userId
                    ORDER BY u.followersCounter DESC, u.username ASC';

        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare($sql);
        $stmt->bindValue('userId', $userId);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function countUserFollowers($userId)
    {
        $sql = 'SELECT COUNT(*) AS counter FROM followers
                WHERE follower_id = :userId';

        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare($sql);
        $stmt->bindValue('userId', $userId);
        $stmt->execute();
        return $stmt->fetch();
    }

    public function countUserFollowing($userId)
    {
        $sql = 'SELECT COUNT(*) AS counter FROM followers
                WHERE followed_id = :userId';

        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare($sql);
        $stmt->bindValue('userId', $userId);
        $stmt->execute();
        return $stmt->fetch();
    }
}
